name: testworkflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v2
        with: 
          node-version: 19
      
      - name: run code
        uses: actions/checkout@v2
  
      - name: run code
        run: node -e 'console.log("hello")
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
      
      - name: checkout
        uses: actions/checkout@v2
  
      - name: run code
        run: python3 -c 'print("hello")
        
       
         
              
      
  
  
